package utils.mutualinformation.misticmod;
/**
 * A class to manage data from MI_data generated by MISTIC
 * 
 * @author javier iserte
 *
 */
public class MI_Position {
	int pos1;
	int pos2;
	String aa1;
	String aa2;
	Double mi;

	public MI_Position(int pos1, int pos2, String aa1, String aa2, Double mi) {
		super();
		this.pos1 = pos1;
		this.pos2 = pos2;
		this.aa1 = aa1;
		this.aa2 = aa2;
		this.mi = mi;
	}

	@Override
	public String toString() {
		return this.pos1 + "\t" + this.aa1 + "\t" + this.pos2 + "\t" + this.aa2+ "\t" + this.mi;
	}
	
	
	/**
	 * Parses MI output from MISTIC
	 * 
	 * @param positionLine
	 * @return
	 */
	public static MI_Position valueOf(String positionLine) { 
		
		String[] data = positionLine.split("\t");
		
		return new MI_Position(Integer.valueOf(data[0]), Integer.valueOf(data[2]), data[1], data[3], Double.valueOf(data[4]));
		
		
	}
	
}

